### ISSUE TITLE
Upon copy what happens to existing configuration in destination site?

### ISSUE THREAD

**Issue by rugcutter284** [gigya/gigya-dev-toolkit#10]
Does the existing configuration and schema get *replaced* with an exact copy from the source site?

What happens to data that is incompatible with schema from the source site?  Is data in the destination truncated?

**Comment by scotthovestadt** [comment]
It's currently impossible to remove schema fields or modify specific properties via the API. Schema fields are only added or modified. If a modification fails, the entire call will fail with an error message.

The exception to this is updating child sites. In that case, properties that cannot be set on a child site are automatically removed and the API call is retried.
