### ISSUE TITLE
Export UI suggests multiple configs can be export when in actuality only 1 is produced

### ISSUE THREAD

**Issue by rugcutter284** [gigya/gigya-dev-toolkit#13]
Repro steps:

1. Goto tool.  Enter user key / secret key, submit
2. Choose Partner ID, submit
3. Choose "Export", submit
4. Under "Settings", choose all 4 checkbox selections (Site Config, Schema, Screensets, Policies).  Submit
5. Choose API Key, submit

Actual Result: only 1 is exported (which one, is undefined)
Expected Result: all 4 configs selected from step 4) are exported

Either make "Settings" radio selections or enable multiple files to be saved tied to the ones selected from checkbox selected.

**Comment by scotthovestadt** [comment]
This appears to be a browser-specific issue. It works in Chrome on my machine.

Can you confirm your browser vendor and version?

Probably triggering multiple file downloads is problematic in some browsers. If I can confirm this is a browser-specific issue I'll set up the tool to zip files together before triggering the download. May also need to offer a download link on the final page to deal with the initial download being blocked by the browser in some cases.

This utility should allow zip archive creation both in-browser and in NodeJS environment:
https://stuk.github.io/jszip/

**Comment by rugcutter284** [comment]
Thanks Scott -

I am using Google Chrome on Mac OS X El Capitan

![image](https://cloud.githubusercontent.com/assets/16804374/13778466/f167214e-ea83-11e5-8097-6bba36e17072.png)
