### ISSUE TITLE
Error: "GigyaDataservice[a] is not a function"

### ISSUE THREAD

**Issue by wi-tokyo** [gigya/gigya-dev-toolkit#20]
Hi Dev Team,

I am getting an error when trying to export screensets:

GigyaDataservice[a] is not a function

Please let me know if you want more information about this issue.

![gigya_toolkit_error](https://cloud.githubusercontent.com/assets/10164020/23119505/e60ac74e-f79b-11e6-9845-f1e0d5d15c14.png)

**Comment by scotthovestadt** [comment]
@wi-tokyo Thanks for letting me know. This was due to a recent update and specifically impacted exporting screen-sets only. I've fixed it and updated the hosted version.

**Comment by wi-tokyo** [comment]
Great, thank you!  I confirmed that it works.
